/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import leetcodeimplementation.app.src.main.java.org.example.MyCircularQueue;

public class App {
   

    public static void main(String[] args) {

        MyCircularQueue obj = new MyCircularQueue(5);
 
        obj.enQueue(50);
        obj.enQueue(70);
        obj.enQueue(71);
        obj.enQueue(72);
        obj.enQueue(80);
        obj.deQueue();
        obj.enQueue(69);

    

        System.out.println(obj.front());
        System.out.println(obj.rear());
    }
}
